# Generated by Django 4.2 on 2026-05-07 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_restricted',
            field=models.BooleanField(default=False, help_text='Designates whether this user has limited access to the platform.'),
        ),
        migrations.AddField(
            model_name='user',
            name='restriction_reason',
            field=models.TextField(blank=True, default='Your account has been restricted by the Admin. Please contact support.', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
