# Generated by Django 4.2 on 2026-05-22 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promo_banner_text', models.CharField(blank=True, default='✨ Use code LUNCH50 to get Tk 60 off on orders over Tk 150 | Available between 12pm - 6pm', max_length=500)),
            ],
        ),
    ]
