# Generated by Django 4.2 on 2026-05-22 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='menu_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='menu.menuitem'),
        ),
    ]
