# Generated by Django 4.2 on 2026-05-22 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_order_rider_alter_order_customer_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Payment Pending', 'Payment Pending'), ('Pending', 'Pending'), ('Preparing', 'Preparing'), ('Ready', 'Ready'), ('Out for Delivery', 'Out for Delivery'), ('Rejected', 'Rejected'), ('Delivered', 'Delivered')], default='Payment Pending', max_length=20),
        ),
    ]
