# Generated by Django 4.2 on 2026-05-22 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0009_order_delivery_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='calories',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
