# Generated by Django 4.2 on 2026-07-05 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0010_menuitem_calories'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='rider_lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='rider_lng',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
